/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deconware.wrappers;

public class YacuDecu_swigJNI {
  public final static native int deconv_device(long jarg1, long jarg2, long jarg3, long jarg4, float[] jarg5, float[] jarg6, float[] jarg7);
}
