/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deconware.wrappers;

public class YacuDecu_swig {
  public static int deconv_device(long iter, long N1, long N2, long N3, float[] h_image, float[] h_psf, float[] h_object) {
    return YacuDecu_swigJNI.deconv_device(iter, N1, N2, N3, h_image, h_psf, h_object);
  }

}
