/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deconware.wrappers;

public class DeconwareSwigJNI {
  public final static native float dot_device(long jarg1, float[] jarg2, float[] jarg3);
}
