/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.deconware.wrappers;

public class DeconwareSwig {
  public static float dot_device(long N, float[] in1, float[] in2) {
    return DeconwareSwigJNI.dot_device(N, in1, in2);
  }

}
